version: "3.9"     
services:          
  mongodb:         
    image: mongo    
    restart: always 
    environment:   
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:        
      - ~/apps/mongo:/data/db
    container_name: "mongodb" 
    ports:               
      - "27017:27017"     
